# PI 1: ETL

## Things to do:

* Trim string values. ✅
* Has duplicate values? NO
* Drop added_date column. ✅
* Create a movies DF
* Manage null values.

## Import Libs

In [47]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

## Create DF's

In [48]:
df_amazon = pd.read_csv('Datasets/amazon_prime_titles.csv')
df_disney = pd.read_csv('Datasets/disney_plus_titles.csv')
df_hulu = pd.read_csv('Datasets/hulu_titles.csv')
df_netflix = pd.read_json('Datasets/netflix_titles.json')

## Trim values

In [49]:
# Remove Leading and Trailing Whitespace

df_amazon = df_amazon.apply(lambda x: x.strip() if type(x) == str else x)
df_disney = df_disney.apply(lambda x: x.strip() if type(x) == str else x)
df_hulu = df_hulu.apply(lambda x: x.strip() if type(x) == str else x)
df_netflix = df_netflix.apply(lambda x: x.strip() if type(x) == str else x)

## Drop date_added column

In [50]:
#Apply strip to al string values.
df_amazon.drop(columns='date_added', inplace=True)
df_disney.drop(columns='date_added', inplace=True)
df_hulu.drop(columns='date_added', inplace=True)
df_netflix.drop(columns='date_added', inplace=True)

## Create a movies DF

In [85]:
#Crate platform table
df_platforms = pd.DataFrame(data= {'platform': ['Amazon', 'Disney', 'Hulu', 'Netflix']})

#Add an platform id column
df_amazon['platform'] = 0
df_disney['platform'] = 1
df_hulu['platform'] = 2
df_netflix['platform'] = 3

df_platforms

  platform
0   Amazon
1   Disney
2     Hulu
3  Netflix

## Manage null values.

,show_id,type,title,director,cast,country,release_year,rating,duration,listed_in,description
0,s1,Movie,Duck the Halls: A Mickey Mouse Christmas Special,"Alonso Ramirez Ramos, Dave Wasson","Chris Diamantopoulos, Tony Anselmo, Tress MacN...",NaN,2016,TV-G,23 min,"Animation, Family",Join Mickey and the gang as they duck the halls!
1,s2,Movie,Ernest Saves Christmas,John Cherry,"Jim Varney, Noelle Parker, Douglas Seale",NaN,1988,PG,91 min,Comedy,Santa Claus passes his magic bag to a new St. ...
3,s4,Movie,The Queen Family Singalong,Hamish Hamilton,"Darren Criss, Adam Lambert, Derek Hough, Alexa...",NaN,2021,TV-PG,41 min,Musical,"This is real life, not just fantasy!"
4,s5,TV Show,The Beatles: Get Back,NaN,"John Lennon, Paul McCartney, George Harrison, ...",NaN,2021,NaN,1 Season,"Docuseries, Historical, Music",A three-part documentary from Peter Jackson ca...
6,s7,TV Show,Hawkeye,NaN,"Jeremy Renner, Hailee Steinfeld, Vera Farmiga,...",NaN,2021,TV-14,1 Season,"Action-Adventure, Superhero",Clint Barton/Hawkeye must team up with skilled...
...,...,...,...,...,...,...,...,...,...,...,...
1418,s1419,Movie,Ye Olden Days,Bert Gillett,NaN,United States,1933,TV-Y7,9 min,"Animation, Comedy, Family",Minnie is locked away for not marrying a princ...
1434,s1435,TV Show,Smart Guy,NaN,"Tahj Mowry, John Jones, Jason Weaver, Essence ...",United States,1996,TV-G,3 Seasons,"Comedy, Coming of Age, Kids",A genius tries to fit in as a high school soph...
1439,s1440,TV Show,Disney Kirby Buckets,NaN,"Jacob Bertrand, Mekai Curtis, Cade Sutton, Oli...",United States,2014,TV-Y7,3 Seasons,"Action-Adventure, Comedy, Coming of Age",Welcome to Kirby's world! It's rude and sketchy.
1440,s1441,TV Show,Disney Mech-X4,NaN,"Nathaniel Potvin, Raymond Cham, Kamran Lucas, ...",Canada,2016,TV-Y7,2 Seasons,"Action-Adventure, Comedy, Science Fiction",Ryan discovers his ability to control a giant ...
1441,s1442,TV Show,Imagination Movers,NaN,"Rich Collins, Dave Poche, Scott Durbin, Scott ...",United States,2008,TV-Y,3 Seasons,"Kids, Music","Rock out with the Imagination Movers, Disney J..."