# PI 1: ETL

## Things to do:

* Trim string values. ✅
* Has duplicate values? NO
* Drop added_date column. ✅
* Manage null values. ✅
* Create a movies DF

## Import Libs

In [279]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

## Create DF's

In [280]:
df_amazon = pd.read_csv('Datasets/amazon_prime_titles.csv')
df_disney = pd.read_csv('Datasets/disney_plus_titles.csv')
df_hulu = pd.read_csv('Datasets/hulu_titles.csv')
df_netflix = pd.read_json('Datasets/netflix_titles.json')

df_amazon

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,NaN,113 min,"Comedy, Drama",A small fishing village must procure a local d...
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,110 min,"Drama, International",A Metro Family decides to fight a Cyber Crimin...
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,"March 30, 2021",2017,NaN,74 min,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...
3,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,"March 30, 2021",2014,NaN,69 min,Documentary,"Pink breaks the mold once again, bringing her ..."
4,s5,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,"March 30, 2021",1989,NaN,45 min,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...
...,...,...,...,...,...,...,...,...,...,...,...,...
9663,s9664,Movie,Pride Of The Bowery,Joseph H. Lewis,"Leo Gorcey, Bobby Jordan",NaN,NaN,1940,7+,60 min,Comedy,New York City street principles get an East Si...
9664,s9665,TV Show,Planet Patrol,NaN,"DICK VOSBURGH, RONNIE STEVENS, LIBBY MORRIS, M...",NaN,NaN,2018,13+,4 Seasons,TV Shows,"This is Earth, 2100AD - and these are the adve..."
9665,s9666,Movie,Outpost,Steve Barker,"Ray Stevenson, Julian Wadham, Richard Brake, M...",NaN,NaN,2008,R,90 min,Action,"In war-torn Eastern Europe, a world-weary grou..."
9666,s9667,TV Show,Maradona: Blessed Dream,NaN,"Esteban Recagno, Ezequiel Stremiz, Luciano Vit...",NaN,NaN,2021,TV-MA,1 Season,"Drama, Sports","The series tells the story of Diego Maradona, ..."
9667,s9668,Movie,Harry Brown,Daniel Barber,"Michael Caine, Emily Mortimer, Joseph Gilgun, ...",NaN,NaN,2010,R,103 min,"Action, Drama, Suspense","Harry Brown, starring two-time Academy Award w..."

## Trim values

In [281]:
# Remove Leading and Trailing Whitespace

df_amazon = df_amazon.apply(lambda x: x.strip() if type(x) == str else x)
df_disney = df_disney.apply(lambda x: x.strip() if type(x) == str else x)
df_hulu = df_hulu.apply(lambda x: x.strip() if type(x) == str else x)
df_netflix = df_netflix.apply(lambda x: x.strip() if type(x) == str else x)

# Normalize string values

df_amazon[['type', 'title', 'director', 'cast', 'country', 'listed_in']] = df_amazon[['type', 'title', 'director', 'cast', 'country', 'listed_in']].apply(lambda x: x.title() if type(x) == str else x)

df_disney[['type', 'title', 'director', 'cast', 'country', 'listed_in']] = df_disney[['type', 'title', 'director', 'cast', 'country', 'listed_in']].apply(lambda x: x.title() if type(x) == str else x)

df_hulu[['type', 'title', 'director', 'cast', 'country', 'listed_in']] = df_hulu[['type', 'title', 'director', 'cast', 'country', 'listed_in']].apply(lambda x: x.title() if type(x) == str else x)

df_netflix[['type', 'title', 'director', 'cast', 'country', 'listed_in']] = df_netflix[['type', 'title', 'director', 'cast', 'country', 'listed_in']].apply(lambda x: x.title() if type(x) == str else x)

## Drop date_added column

In [282]:
#Apply strip to al string values.
df_amazon.drop(columns='date_added', inplace=True)
df_disney.drop(columns='date_added', inplace=True)
df_hulu.drop(columns='date_added', inplace=True)
df_netflix.drop(columns='date_added', inplace=True)

## Create a movies DF

In [283]:
#Add an platform column.
df_amazon['platform'] = 'amazon'
df_disney['platform'] = 'disney'
df_hulu['platform'] = 'hulu'
df_netflix['platform'] = 'netflix'

## Manage null values.

In [284]:
#set title column as index

df_amazon.set_index('title', drop=True, inplace=True)
df_disney.set_index('title', drop=True, inplace=True)
df_hulu.set_index('title', drop=True, inplace=True)
df_netflix.set_index('title', drop=True, inplace=True)

#Filling amazon null values with fillna
# fillna match with the index and column

df_amazon.fillna(df_disney, inplace=True)
df_amazon.fillna(df_hulu, inplace=True)
df_amazon.fillna(df_netflix, inplace=True)

df_disney.fillna(df_amazon, inplace=True)
df_disney.fillna(df_hulu, inplace=True)
df_disney.fillna(df_netflix, inplace=True)

df_hulu.fillna(df_amazon, inplace=True)
df_hulu.fillna(df_disney, inplace=True)
df_hulu.fillna(df_netflix, inplace=True)

df_netflix.fillna(df_amazon, inplace=True)
df_netflix.fillna(df_disney, inplace=True)
df_netflix.fillna(df_hulu, inplace=True)

#Revert set_index.

df_amazon.reset_index(inplace=True)
df_disney.reset_index(inplace=True)
df_hulu.reset_index(inplace=True)
df_netflix.reset_index(inplace=True)

## Divide general DF to movies and Tv Shows

In [285]:
df_general = pd.concat([df_amazon, df_netflix, df_disney, df_hulu])
#Change name of column listed_in to genre for better comprehension
df_general.rename(columns= {'listed_in': 'genre'}, inplace=True)
#Lowercase to all genres
df_general.genre = df_general.genre.apply(lambda x: x.lower())


df_movies = df_general[df_general['type'] == "Movie"]
df_tv_shows = df_general[df_general['type'] == 'TV Show']

df_movies.reset_index(drop=True, inplace=True)
df_movies.reset_index(drop=True, inplace=True)

In [286]:
len(df_movies.director.unique().tolist())

df_movies

,title,show_id,type,director,cast,country,release_year,rating,duration,genre,description,platform
0,The Grand Seduction,s1,Movie,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,2014,NaN,113 min,"comedy, drama",A small fishing village must procure a local d...,amazon
1,Take Care Good Night,s2,Movie,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,2018,13+,110 min,"drama, international",A Metro Family decides to fight a Cyber Crimin...,amazon
2,Secrets of Deception,s3,Movie,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,2017,NaN,74 min,"action, drama, suspense",After a man discovers his wife is cheating on ...,amazon
3,Pink: Staying True,s4,Movie,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,2014,NaN,69 min,documentary,"Pink breaks the mold once again, bringing her ...",amazon
4,Monster Maker,s5,Movie,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,1989,NaN,45 min,"drama, fantasy",Teenage Matt Banting wants to work with a famo...,amazon
...,...,...,...,...,...,...,...,...,...,...,...,...
16474,All Saints (1998),s2952,Movie,NaN,NaN,Australia,1998,12 Seasons,NaN,"drama, international",All Saints is an Australian medical drama focu...,hulu
16475,(Sub) Ninja Scroll,s2959,Movie,NaN,NaN,Japan,1993,93 min,NaN,"action, adult animation, adventure",When Jubei saves a young ninja woman from the ...,hulu
16476,Packed to the Rafters,s2960,Movie,NaN,NaN,Australia,2008,6 Seasons,NaN,"comedy, drama, international",Packed to the Rafters is an Australian family-...,hulu
16477,(Sub) Legend of Heroes: Trails in the Sky,s2983,Movie,NaN,NaN,NaN,2011,PG-13,84 min,"anime, international, science fiction","Ten years ago, an invasion by the Erebonians a...",hulu
16478,Amy Winehouse: A Final Goodbye,s2994,Movie,NaN,NaN,United Kingdom,2011,71 min,NaN,"documentaries, music",A Final Goodbye is an intimate look into the l...,hulu

In [287]:
#correct load errors
df_movies.loc[16205, 'duration'] = df_movies.loc[16205, 'rating']
df_movies.loc[16205, 'rating'] = np.nan

df_movies.loc[16311, 'duration'] = df_movies.loc[16205, 'rating']
df_movies.loc[16311, 'rating'] = np.nan

df_movies[df_movies['duration'] == '3 Seasons'] #Edit directly in the hulu_titles.csv the type to TV_SHOW

df_movies[df_movies['duration'] == '6 Seasons']#Edit directly in the hulu_titles.csv the type to TV_SHOW

Empty DataFrame
Columns: [title, show_id, type, director, cast, country, release_year, rating, duration, genre, description, platform]
Index: []

In [288]:
#Manage duration of df_tv

df_tv_shows['duration'] = df_tv_shows['duration'].apply(lambda x: x.split(' ') if type(x) == str else x)

df_tv_shows['duration'] = df_tv_shows['duration'].apply(lambda x: x.pop(0) if type(x) == list else x)

df_tv_shows['duration'] = pd.to_numeric(df_tv_shows['duration'])

df_movies['duration'] = df_movies['duration'].apply(lambda x: x.split(' ') if type(x) == str else x)

df_movies['duration'] = df_movies['duration'].apply(lambda x: x.pop(0) if type(x) == list else x)

df_movies['duration'] = pd.to_numeric(df_movies['duration'])

C:\Users\ESEQUIEL\AppData\Local\Temp\ipykernel_4704\2860903579.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_tv_shows['duration'] = df_tv_shows['duration'].apply(lambda x: x.split(' ') if type(x) == str else x)
C:\Users\ESEQUIEL\AppData\Local\Temp\ipykernel_4704\2860903579.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_tv_shows['duration'] = df_tv_shows['duration'].apply(lambda x: x.pop(0) if type(x) == list else x)
C:\Users\ESEQUIEL\AppData\Local\Temp\ipykernel_4704\2860903579.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_tv_shows['duration'] = pd.to_numeric(df_tv_shows['duration'])
C:\Users\ESEQUIEL\AppData\Local\Temp\ipykernel_4704\2860903579.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_movies['duration'] = df_movies['duration'].apply(lambda x: x.split(' ') if type(x) == str else x)
C:\Users\ESEQUIEL\AppData\Local\Temp\ipykernel_4704\2860903579.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_movies['duration'] = df_movies['duration'].apply(lambda x: x.pop(0) if type(x) == list else x)
C:\Users\ESEQUIEL\AppData\Local\Temp\ipykernel_4704\2860903579.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_movies['duration'] = pd.to_numeric(df_movies['duration'])

## Create Dimension Dataframes

In [289]:
# Directors

#error strings:
err_string_1 = 'CAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI ValidCAPI'


df_movies['director'] = df_movies.director.fillna('No Data')#Fill nan 
df_movies['director'].replace(err_string_1, 'No Data', inplace=True)# Mange error strings
df_tv_shows['director'] = df_tv_shows.director.fillna('No Data')#Fill nan 
df_tv_shows['director'].replace(err_string_1, 'No Data', inplace=True)#Manage error strings

#List with uni values of director names
director_names = df_movies.director.unique().tolist() 
director_names += df_tv_shows.director.unique().tolist() #Concat lists

#print(director_names) #Len for solve 3 error in the final of the list

# Search rare strings
#for ind, cont in enumerate(director_names):
#    if len(cont) > 100:
#        print("Indice: ", ind, end='\n\n')
#        print(cont)

#Solve 3 errors
director_names[9949] = 'Jennifer Kent'
director_names[9950] = 'Gigi Saul Guerrero'
director_names[9951] = 'Alex Winter'

#Split strings wit ', '.
for ind, cont in enumerate(director_names):
    director_names[ind] = cont.split(", ")

#tranform to a 1D list
director_names = list(np.concatenate(director_names).flat)

#Trim values
for ind, cont in enumerate(director_names):
    director_names[ind] = cont.strip()

#remove duplicated values
director_names = list(set(director_names))

#create dataframe
df_directors = pd.DataFrame({'name': director_names})

df_directors['name']

C:\Users\ESEQUIEL\AppData\Local\Temp\ipykernel_4704\1031052520.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_movies['director'] = df_movies.director.fillna('No Data')#Fill nan
C:\Users\ESEQUIEL\AppData\Local\Temp\ipykernel_4704\1031052520.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_movies['director'].replace(err_string_1, 'No Data', inplace=True)# Mange error strings
C:\Users\ESEQUIEL\AppData\Local\Temp\ipykernel_4704\1031052520.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_tv_shows['director'] = df_tv_shows.director.fillna('No Data')#Fill nan
C:\Users\ESEQUIEL\AppData\Local\Temp\ipykernel_4704\1031052520.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_tv_shows['director'].replace(err_string_1, 'No Data', inplace=True)#Manage error strings

0           Pietro Scappini
1               David Batty
2         Savvas D. Michael
3              Terry Spears
4                Will Young
                ...
10889      Isaac Florentine
10890     Andreas Prochaska
10891         Mark Obenhaus
10892    Lucas James McGraw
10893           Thor Moreno
Name: name, Length: 10894, dtype: object

## Replace values of movies and tv show dataframes

In [290]:
#Replace error of director in movies dataframe:

err_string_2 = "Director Gigi Saul Guerrero talks through Culture Shock’s themes – immigration, filmmaking, and latinidad – in this one-on-one chat."

err_string_3 = "Alex Winter goes inside the biggest global corruption scandal in history that was uncovered by hundreds of journalists, working in secret and at enormous risk."

df_movies[df_movies['director'].str.find(("The Babadook")) != -1]
df_movies.loc[16184, 'director'] = 'Jennifer Kent'

df_movies[df_movies['director'].str.find((err_string_2)) != -1]
df_movies.loc[16213, 'director'] = 'Gigi Saul Guerrero'

df_movies[df_movies['director'].str.find((err_string_3)) != -1]
df_movies.loc[16307, 'director'] = 'Alex Winter'

## Export csv

In [291]:
df_movies.to_csv('app/Data/movies.csv', index=False)
df_tv_shows.to_csv('app/Data/tv_shows.csv', index=False)